### ISSUE TITLE
DB-User

### ISSUE THREAD

**Issue by Zweistein2** [Zweistein2/ProjectOmega#17]
Anlegen eines Datenbank-Users mit Zugriffen auf die Testdaten.

**Comment by paulusd** [comment]
[itv_v02.txt](https://github.com/Zweistein2/ProjectOmega/files/1169686/itv_v02.txt)

**Comment by paulusd** [comment]
@Zweistein2 
Name der DB?
Name des Users?

**Comment by Zweistein2** [comment]
Username: Software_test
DBname: Wie ihr die halt genannt habt, weiß ich ja nicht. Die wo wir halt unsere Testdaten ablegen können. Struktur wie in der produktiven Datenbank, deren dump wir ja haben.

**Comment by paulusd** [comment]
Bitte prüfen ob db so stimmt

DB: softwareTest
User: dev
pw:dev
