### ISSUE TITLE
Deploy key

### ISSUE THREAD

**Issue by paulusd** [Zweistein2/ProjectOmega#18]
@Zweistein2 
Bitte den Deploy key eintragen

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDHYIZjxLJhlJrsuCHJ3kvKlg5wfhnpzOErn7Z0qDZxuatBi7+xGjT7j2AEd1QGVsHLftt3UifTgn1MZtABaVaAaHS63QkDk30Fl9MKHAxIUtzp2pwYfJbmOTBstz4Hpfkex44OnWE7nwNtzHvVH9NDMRf4BuLjRlt7qsWdraiB/i8Dv2QAKVMI/Ue0/hvGircHSzpPa0yYmUL/Aj8KCz3Pb2eT1pDGhEX8RqpBD2g8jvg/w0S5tXOa2z1jsyMzgxRVgsa0fAqbw7UE4vs5zDL9TseRZ9av3B/f5O5FSAx5XBnIbBXQFFgQ6wv4/Zcd/YDy5ddDg6w68gwttV1Vmq2wtJvI19h8xdt0Wc93+H863ziRRcJIu71Dvwb9imcb1k0orMQGqP5RzLS9GhP4dBFXPFpabbvbDhsY88PrtE08Ko/+T9iJ6QhriN5B1IsUX3M9TyFk4ndsV36X/7Oc2lHre2qdmPZbcMA/xXpEb7Sn2jIJMY9lj3HF0IQOppB15/cYgOiwnSpLpWMC/p1F/fWUElcw+EBdvd4Id83/dzgXya38CuQa9urHocKDyeoEV2XTH8mP+Qfzj8UF5KKOy8xqqQ/tJsqzn+CX0kY87kOGeWy0/7jpWsBgfIGz0KMba1lVSKosC3YFcFl9lK1+ORcfS4D86b2VaaiHdWMmanR5sw== root@localhost.localdomain

**Comment by Zweistein2** [comment]
Erledigt.
