### ISSUE TITLE
Erstellen der Anmeldung

### ISSUE THREAD

**Issue by Zweistein2** [Zweistein2/ProjectOmega#24]
Schreiben von PHP-Code

- [x] Rechtesystem
- [x] Session
- [x] Passwort Hashen
- [x] Datenbanktabelle
- [x] Datenbank Abfragen für die Stammdatenverwaltung schreiben  
- [x] Navbar erweitern (Tab hervorheben auf dem man ist)

Aufgabe von PO:

- [x] Review

**Comment by BasementPilot** [comment]
Die Struktur für die Benutzer wurde angelegt #32
