### ISSUE TITLE
DB für die Benutzer anlegen

### ISSUE THREAD

**Issue by BasementPilot** [Zweistein2/ProjectOmega#32]
Hier die Struktur für die Datenbank:
[nutzer.txt](https://github.com/Zweistein2/ProjectOmega/files/1173168/nutzer.txt)

**Comment by BasementPilot** [comment]
Bitte bei der 'users' Tabelle die Spalte 'username' noch auf unique stellen.

**Comment by paulusd** [comment]
erledigt
