### ISSUE TITLE
logisches modell

### ISSUE THREAD

**Issue by intraduct** [Zweistein2/ProjectOmega#39]
[logisches modell db.zip](https://github.com/Zweistein2/ProjectOmega/files/1175604/logisches.modell.db.zip)

**Comment by intraduct** [comment]
@Zweistein2

**Comment by Zweistein2** [comment]
[DB2.pdf](https://github.com/Zweistein2/ProjectOmega/files/1175637/DB2.pdf)
[DB1.pdf](https://github.com/Zweistein2/ProjectOmega/files/1175638/DB1.pdf)

Konvertiert als PDF
